project_id: '591751'
api_token: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/*.arb
    translation: /lib/l10n/app_%two_letters_code%.arb
