name: file_manager
description: The file manager for the Expidus operating system.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: feat/packages
      path: packages/libtokyo_flutter
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  bitsdojo_window: ^0.1.5
  xdg_directories: ^1.0.0
  universal_disk_space: ^0.2.3
  udisks: ^0.4.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  saf: ^1.0.3+4
  open_file_plus: ^3.4.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - imgs/
