name: file_manager
description: The file manager for the Expidus operating system.
publish_to: 'none'
version: 0.2.1+65656565656565
homepage: https://expidusos.com
funding:
  - https://opencollective.com/expidusos

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo_flutter
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  bitsdojo_window: ^0.1.5
  xdg_directories: ^1.0.0
  udisks: ^0.4.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  open_file_plus: ^3.4.1
  permission_handler: ^10.2.0
  win32: ^3.1.4
  path_provider_windows: ^2.1.6
  path_provider_platform_interface: ^2.0.6
  ffi: ^2.0.2
  sentry_flutter: ^7.6.2
  pubspec: ^2.3.0
  filesize: ^2.0.1
  intl: ^0.18.0
  provider: ^6.0.5
  flutter_markdown: ^0.6.15
  flutter_adaptive_scaffold: ^0.1.4
  package_info_plus: ^3.1.2
  pub_semver: ^2.1.4

dependency_overrides:
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/
    - pubspec.yaml
    - .dart_tool/package_config.json
    - PRIVACY.md
