name: Flutter
on: push

jobs:
  build:
    strategy:
      matrix:
        arch: [x64]
        channel: [stable]
        target: [linux, windows, macos, android]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
            - os: ubuntu-latest
              target: windows
            - os: ubuntu-latest
              target: macos
            - os: windows-latest
              target: linux
            - os: windows-latest
              target: macos
            - os: macos-latest
              target: windows
            - os: macos-latest
              target: linux
            - os: windows-latest
              target: android
            - os: macos-latest
              target: android
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: ${{ matrix.channel }}
          architecture: ${{ matrix.arch }}
      - if: ${{ matrix.target == 'android' }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - if: ${{ matrix.target == 'linux' }}
        name: Install host dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev flatpak-builder
      - run: flutter doctor
      - name: Download dependencies
        run: flutter pub get
      - if: ${{ matrix.target != 'android' }}
        name: Build desktop
        run: |
          flutter config --enable-${{ matrix.target }}-desktop
          flutter build ${{ matrix.target }} --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
      - if: ${{ matrix.target == 'linux' }}
        name: Bundle Flatpak
        run: flatpak-builder build/flutter data/com.expidusos.file_manager.yml
      - if: ${{ matrix.target == 'android' }}
        name: Build for Android
        run: |
          flutter build apk --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
