name: Flutter
on: push

jobs:
  linux:
    strategy:
      matrix:
        arch: [x64]
        channel: [stable]
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Add missing dependencies
        run: |
          dnf update -y
          dnf install -y jq
          dnf clean all
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: ${{ matrix.channel }}
          architecture: ${{ matrix.arch }}
      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        name: Bundle Flatpak
        with:
          bundle: com.expidusos.file_manager.flatpak
          manifest-path: data/com.expidusos.file_manager.yml
          cache-key: flatpak-builder-${{ github.sha }}
  build:
    strategy:
      matrix:
        arch: [x64]
        channel: [stable]
        target: [windows, macos, android]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
            - os: ubuntu-latest
              target: windows
            - os: ubuntu-latest
              target: macos
            - os: windows-latest
              target: macos
            - os: macos-latest
              target: windows
            - os: windows-latest
              target: android
            - os: macos-latest
              target: android
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: ${{ matrix.channel }}
          architecture: ${{ matrix.arch }}
      - if: ${{ matrix.target == 'android' }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter doctor
      - name: Download dependencies
        run: flutter pub get
      - if: ${{ matrix.target != 'android' }}
        name: Build desktop
        run: |
          flutter config --enable-${{ matrix.target }}-desktop
          flutter build ${{ matrix.target }} --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
      - if: ${{ matrix.target == 'android' }}
        name: Build for Android
        run: |
          flutter build apk --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
